### ISSUE TITLE
Setting daemon=True for classes when constructing?

### ISSUE THREAD

**Issue by KyleBenson** [KyleBenson/SmartAmericaSensors#18]
I'm not sure what this is doing, but it should really be handled from inside the class constructor itself rather than from the outside.

**Comment by bfrggit** [comment]
It seemed that if you don't do that, the threads will not receive the termination signal from the main thread, which prevents them from being terminated with `Ctrl`+`C`.

No longer a problem is the `circuit` based "threading".
