### ISSUE TITLE
Geo-location tagging feature

### ISSUE THREAD

**Issue by KyleBenson** [KyleBenson/SmartAmericaSensors#24]
Some mechanism for tagging SensedEvents with geo-location data.  Two options:

1) Gather info from online service based on IP address and perturb them slightly (possibly zeroing in on known locations first, e.g. DBH, Thingstitute, etc.) so that not all markers are on the same exact point.
2) Assign specific rooms to each SCALE box.  This could either be stored as a value in the local config file or it could be in a database somewhere, which will require rethinking how the data flows to the dashboard as it will either have to have this tag when it arrives or the dashboard will have to do this lookup itself (which is probably the easiest?  just a RESTful endpoint on the SCALE server...)

**Comment by bfrggit** [comment]
How about we make a mock-location VS that simply outputs a fake location? It can have its own mechanisms on how to generate these values, e.g. look up some table with its MAC address...
Geo tags are not fully implemented yet. I'll think of this after I finish the geo tagging part on EventReporter.

**Comment by KyleBenson** [comment]
That sounds like a fine start to me. We can add a better version later if
we decide to do so and use this as a fallback.

**Comment by bfrggit** [comment]
GeoIPVirtualSensor is implemented.
I also implemented a FakeLocationVirtualSensor which allows you to define `lat` and `lon` just in configuration files.
